[build-system]
requires = ["uv_build >=0.12.1, <0.13.0"]
build-backend = "uv_build"

[project]
name = "crochet"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
    "stim>=1.16.0",
    "termcolor>=3.3.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
]

[project.scripts]
crochet = "crochet.cli:main"
